### ISSUE TITLE
Automate loadEnvTest

### ISSUE THREAD

**Issue by fennesz** [AllToTheX/RemotePython#12]
As per the TODO in the unittest file, testing the environment on the remote machine should create a file and clean up on the remote machine automatically.

Want me to look into it?

**Comment by AllToTheX** [comment]
If you want to, please do.

**Comment by AllToTheX** [comment]
Added your changes, made some minor adjustments to also delete ./bin if it didn't exist before we created it. Although I just now realise this might not work in C shell.. ah well.. it's only a test.
