### ISSUE TITLE
Allow setting of load environment file on object level

### ISSUE THREAD

**Issue by AllToTheX** [AllToTheX/RemotePython#6]
different Linux versions use different files to load the environment.
Think up a way to load the correct one without defining the in code.

**Comment by fennesz** [comment]
I am guessing the underlying issue here is that you need to load the environment variables to execute python scripts? Because I don't seem to be getting any errors.

I am running Linux 3.19.0-30-generic #34-Ubuntu. If I set RemotePython getEnv() to return an empty string, all unittests still pass no matter if I do them locally or on my raspberry pi. I can also echo environment variables that SSH doesn't set.

**Comment by fennesz** [comment]
In any case, and I'm not sure if this is helpful or not, but it looks like SSH automatically adds environment variables from ~/.ssh/environment. This is from the man file:

> Additionally, ssh reads ~/.ssh/environment, and adds lines of the format
     “VARNAME=value” to the environment if the file exists and users are
     allowed to change their environment.  For more information, see the
     PermitUserEnvironment option in sshd_config(5).

**Comment by AllToTheX** [comment]
the issue is that I need to call commands that are in my user /bin, which don't get added to the $PATH if i log in using ssh to run a command. (not a login or interactive shell)
I've fixed this today but want to test it on a Solaris machine before commiting

**Comment by AllToTheX** [comment]
What i'm planning to do is check what shell i'm using and source the files that the shell would source by default. so for bash this would be .bash_profile .bash_login and .profile, whichever is present first. on csh (C shell) this would be .login

**Comment by AllToTheX** [comment]
but what would you want to use this for? maybe we can add some specific functionality for your project

**Comment by fennesz** [comment]
So I'm planning to use it for easy deployment of some OpenCV scripts on a Raspberry Pi. I'm not sure exactly what it is going to involve as of yet, and I doubt that I'll need extra functionality beyond that. But it's nice automate the process in such a way that all the necessary tests can be run on the target, without having to send a lot of stuff back and forth. It's also why I had the idea about sshpass.

I'll think about additional features. Maye I'll come up with something. :)
