### ISSUE TITLE
Too many password requests in unittest

### ISSUE THREAD

**Issue by fennesz** [AllToTheX/RemotePython#7]
Running the unit test prompts for password each time the runcommand is written. Using sshpass instead of ssh?

**Comment by fennesz** [comment]
The command sshpass -e grabs the password from the SSHPASS environment variable.

**Comment by AllToTheX** [comment]
Good point, could add it as an optional

**Comment by fennesz** [comment]
Hello Alex, glad to hear you agree. I've added the functionality now, and it passes my own unit tests. I'll be making a pull request soon.

**Comment by AllToTheX** [comment]
make sure to rebase (merge I think it's call in git). I've made some changes to the calls of runCommand and runScript

**Comment by fennesz** [comment]
Thanks for the heads up. I pulled and merged again - and have now submitted a pull request with the changes.

This is my first time contributing to a project on Github, so if there's anything I ought to do differently let me know. I'll close the issue once (And if) you accept the pull request.

**Comment by AllToTheX** [comment]
Added my comments to your pull request, I'm a little strict as I use this script at work as well.
I'm happy you're contributing so keep it up! (my first project where someone is contributing as well)

**Comment by fennesz** [comment]
Happy to be contributing! I'm a fourth semester software engineer, and I'm doing this to learn python, learn how to collaborate on projects, how to read others code, etc. Besides, this project is pretty useful for a project here at home I want to do with my Raspberry Pi.

**Comment by AllToTheX** [comment]
Nice, I pulled your changes and will close this issue.
