### ISSUE TITLE
More testcases for errorhandling

### ISSUE THREAD

**Issue by fennesz** [AllToTheX/RemotePython#9]
I have begun writing testcases that makes sure RemotePython handles errors in runScript as expected like so:

```
def testRunScriptValueError(self):
        ''' Test that ValueError is raised when RemotePython doesn't receive a script'''
        obj = RemotePython()
        with self.assertRaises(ValueError):
            obj.runScript()
```

I was thinking testcases like these will help make sure errorhandling in general works as expected. Ideas or comments?

**Comment by AllToTheX** [comment]
I might redo the error handling in the future so a proper test case for error handling would certainly help.

**Comment by fennesz** [comment]
Great. I'll work on that! I will make them generalized and test for concrete exceptions. Testing is bearable now that sshpass is implemented.

**Comment by fennesz** [comment]
Making a pull request with a few testcases for runScript now, just to see if I'm on the right track.
